dataset:
  repo_id: omy_base_data      # <--- 对应 Base 数据集的 ID
  root: ./demo_data_base      # <--- 对应 Base 数据集的本地路径

policy:
  type: pi0
  chunk_size: 20              # 导航任务通常具有较长的连续性，稍大的 chunk 可能更平滑
  n_action_steps: 20
  use_amp: false
  attention_implementation: sdpa

save_checkpoint: true
output_dir: ./ckpt/pi0_base   # <--- 修改输出目录
batch_size: 16
job_name: pi0_base
resume: false
seed: 42
num_workers: 4
steps: 25000                  # 导航（如果只是简单的移动）通常比抓取收敛快

eval_freq: -1
log_freq: 50
save_freq: 10000
use_policy_training_preset: true

wandb:
  enable: true
  project: omy_robot_project
  entity: "2466893086-"
  disable_artifact: true